print("##############################\n")
print("#                            #\n")
print("#    Laily Azizah Islami     #\n")
print("#      2510817220020         #\n")
print("#                            #\n")
print("##############################\n")